### ISSUE TITLE
What is the format of the data?

### ISSUE THREAD

**Issue by IrvingBei** [MokkeMeguru/simple-copynet#1]
Hi, thanks for sharing this code, I can't run this code successfully when I don't know the data format. Could you give me an example of the format of the data or send me the data files that are using by you. Thanks again!

**Comment by MokkeMeguru** [comment]
see. https://github.com/MokkeMeguru/simple-copynet/blob/master/trainfromcsv.ipynb
https://github.com/MokkeMeguru/st-data is same as "./st-data/base.csv".

NOTICE: This repository is for sentences' style transfer.
IDEA: Differences between styled sentence and non-styled sentence are generated by some words. (Especially in Japanese)

**Comment by MokkeMeguru** [comment]
Sorry for the late reply ...

**Comment by MokkeMeguru** [comment]
ex.
line.x in base.csv
hello

line.x in styled.csv
hi!

**Comment by IrvingBei** [comment]
Thank you very much for your detailed reply, I also finished this experiment. Thanks again
